# use latest version of ubuntu as the base img
FROM ubuntu:latest

# updates APT and upgrades install software
RUN apt-get update && apt-get upgrade -y

# define the command that runs when the container starts
CMD echo "Hello, World!"