version: '3'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile